### ISSUE TITLE
Delete background of the bar to keep the circle 

### ISSUE THREAD

**Issue by comelaine** [ozmartian/QRoundProgressBar#2]
![image](https://user-images.githubusercontent.com/76111749/102891735-04eaa300-445f-11eb-8e28-9411998d9d03.png)

Hi 
I am trying to get rid of the background behind the round bar. 
I tried a lot of things but at the end i get theses bugs.
Did anyone succeed this kind of attempt ?

**Comment by ozmartian** [comment]
Back when I wrote this I couldn't get it figured out. I simply ported the C++ to Python.
